channels:
- currentCSV: ibm-ingress-nginx-operator.v1.2.2
  name: dev
- currentCSV: ibm-ingress-nginx-operator.v1.2.2
  name: beta
- currentCSV: ibm-ingress-nginx-operator.v1.2.2
  name: stable-v1
defaultChannel: stable-v1
packageName: ibm-ingress-nginx-operator-app
