# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.defaultBackend.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Values.defaultBackend.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: nginx-ingress-controller 
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
  name: {{ .Values.defaultBackend.name }}
spec:
  selector:
    matchLabels:
      app: "{{ .Values.defaultBackend.name }}"
      chart: "{{ .Chart.Name }}"
      heritage: "{{ .Release.Service }}"
      component: "{{ .Values.defaultBackend.name }}"
      release: {{ .Release.Name }}
  {{- if .Values.defaultBackend.replicas }}
  replicas: {{ .Values.defaultBackend.replicas }}
  {{- else }}
  replicas: {{ .Values.defaultBackend.replicaCount }}
  {{- end }}
  template:
    metadata:
      annotations:
        productName: "IBM Cloud Platform Common Services"
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: "FREE"
        clusterhealth.ibm.com/dependencies: ""
      labels:
        app: "{{ .Values.defaultBackend.name }}"
        chart: "{{ .Chart.Name }}"
        heritage: "{{ .Release.Service }}"
        component: "{{ .Values.defaultBackend.name }}"
        release: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ .Release.Name }}
        helm.sh/chart: {{ .Chart.Name }}
        app.kubernetes.io/instance: nginx-ingress-controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.defaultBackend.name }}
                - key: component
                  operator: In
                  values:
                  - {{ .Values.defaultBackend.name }}
              topologyKey: kubernetes.io/hostname
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            key: app
            values: {{ .Values.defaultBackend.name }}
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/region
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            key: app
            values: {{ .Values.defaultBackend.name }}
      serviceAccount: nginx-ingress
      serviceAccountName: nginx-ingress
      containers:
        - name: default-http-backend
          {{- if .Values.defaultBackend.imageDigest }}
          image: {{ .Values.defaultBackend.imageDigest }}
          {{- else }}
          image: "{{ .Values.defaultBackend.imageRegistry }}/{{ .Values.defaultBackend.image.repository }}:{{ .Values.defaultBackend.image.tag }}"
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          imagePullPolicy: "{{ .Values.defaultBackend.image.pullPolicy }}"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: "/healthz"
              scheme: HTTP
              port: 8080
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
{{ toYaml .Values.defaultBackend.resources | indent 12 }}
      nodeSelector:
{{ toYaml .Values.defaultBackend.nodeSelector | indent 8 }}
      tolerations:
{{ toYaml .Values.defaultBackend.tolerations | indent 8 }}
