apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "operator.ibm.com/v1alpha1",
          "kind": "NginxIngress",
          "metadata": {
            "name": "example"
          },
          "spec": {
            "defaultBackend": {
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "quay.io/default-http-backend",
                "tag": "1.5.2"
              },
              "name": "default-http-backend",
              "nodeSelector": {},
              "replicaCount": 1,
              "resources": {
                "requests": {
                  "cpu": "20m",
                  "memory": "64Mi"
                }
              },
              "tolerations": []
            },
            "fips_enabled": false,
            "ingress": {
              "annotations": {},
              "config": {
                "disable-access-log": "true",
                "keep-alive-requests": "10000",
                "server-tokens": "false",
                "upstream-keepalive-connections": "64"
              },
              "extraArgs": {},
              "hostNetwork": false,
              "hostPort": false,
              "httpPort": 80,
              "httpsPort": 443,
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "quay.io/nginx-ingress-controller",
                "tag": "0.23.0"
              },
              "name": "nginx-ingress-controller",
              "nodeSelector": {},
              "replicaCount": 1,
              "resources": {
                "requests": {
                  "cpu": "50m",
                  "memory": "256Mi"
                }
              },
              "routeHost": "cp-proxy.apps.ibm.com",
              "tolerations": []
            },
            "init": {
              "image": {
                "pullPolicy": "IfNotPresent",
                "repository": "quay.io/icp-initcontainer",
                "tag": "1.0.0-build.2"
              }
            }
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-ingress-nginx-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NginxIngress is the Schema for the nginxingress API
      group: operator.ibm.com
      kind: NginxIngress
      name: nginxingresses.operator.ibm.com
      version: v1alpha1
      displayName: IBM Ingress nginx Operator
      resources:
      - kind: Deployment
        name: ibm-ingress-nginx-operator
        version: v1
      - kind: Service
        name: ibm-ingress-nginx-operator
        version: v1
      - kind: Configmap
        name: ibm-ingress-nginx-operator
        version: v1
      specDescriptors:
      - description: Image of Ingress nginx controller
        displayName: Image of Ingress nginx controller
        path: spec.ingress.image
      - description: Image of Default http backend
        displayName: Image of Default http backend
        path: spec.defaultBackend.image
      - description: OCP route host of Ingress nginx controller
        displayName: Route Host of Ingress nginx controller
        path: spec.ingress.routeHost
      - description: Number of instance for Ingress nginx controller
        displayName: Replica of Ingress nginx controller
        path: spec.ingress.replicaCount
      - description: Whether to enable FIPS encryption
        displayName: Enable FIPS encryption
        path: spec.fips_enabled
  description: Ibm Ingress Nginx Operator
  displayName: Ibm Ingress Nginx Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - configmaps
          - pods
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - '*'
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - ibm-ingress-nginx-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - operator.ibm.com
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: ibm-ingress-nginx-operator
      deployments:
      - name: ibm-ingress-nginx-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-ingress-nginx-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-ingress-nginx-operator
            spec:
              containers:
              - env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-ingress-nginx-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: ibm-ingress-nginx-operator
                resources: {}
              serviceAccountName: ibm-ingress-nginx-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider:
    name: IBM
  replaces: ibm-ingress-nginx-operator.v0.0.0
  version: 0.0.1
