# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Whether to enable FIPS
fips_enabled: false

# Config related with ingress nginx controller
ingress:
  name: nginx-ingress-controller
  replicaCount: 1
  replicas: 1
  hostNetwork: false
  hostPort: false
  httpPort: 7080
  httpsPort: 7443
  routeHost: ""
  imageRegistry: quay.io/opencloudio
  imageDigest: quay.io/opencloudio/nginx-ingress-controller@sha256:4c8ad1a75ece03342f0c479769c0332ab6be5565b7a456954b23b022cc109759
  image:
    repository: nginx-ingress-controller
    tag: 0.23.5
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 200m
      memory: 512Mi
  config:
    disable-access-log: 'true'
    keep-alive-requests: '10000'
    upstream-keepalive-connections: '64'
    server-tokens: 'false'
    ssl-ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256'
  extraArgs: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  watchNamespace: []

# Config related with default http backend
defaultBackend:
  name: default-http-backend
  replicaCount: 1
  replicas: 1
  imageRegistry: quay.io/opencloudio
  imageDigest: quay.io/opencloudio/default-http-backend@sha256:2a5e3bfe7a771d36ad186e2ab8303ea2fbb854b4a7437e7c3b3f1d8e87d9e286
  image:
    repository: default-http-backend
    tag: 1.5.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []

# The init image used to configure some system setting
init:
  imageDigest: quay.io/opencloudio/icp-initcontainer@sha256:c0820a378fe87f79e0d553e3ff0bc4dc3d2d3312b7b6ae0c788f9bfe8a632966
  imageRegistry: quay.io/opencloudio
  image:
    repository: icp-initcontainer
    tag: 1.0.0-build.4
    pullPolicy: IfNotPresent

# The kubectl image used to patch route resource
kubectl:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  imageDigest: quay.io/opencloudio/kubectl@sha256:8d8e730df85c925287c6db21801ef426a155500740447ae43f7f88d5e2b0aeef
  imageRegistry: quay.io/opencloudio
  image:
    repository: kubectl
    tag: v1.15.9.3
