# Licensed Materials - Property of IBM
# Copyright IBM Corporation 2016,2021. All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Whether to enable FIPS
fips_enabled: false

# Config related with ingress nginx controller
ingress:
  name: nginx-ingress-controller
  replicaCount: 1
  replicas: 1
  hostNetwork: false
  hostPort: false
  httpPort: 7080
  httpsPort: 7443
  routeHost: ""
  imageRegistry: quay.io/opencloudio
  imageDigest: quay.io/opencloudio/nginx-ingress-controller@sha256:572eb9a2e503e3643bd85454fb36ef23761367bf3d0b54fb9a287d406bcc677e
  image:
    repository: nginx-ingress-controller
    tag: 0.23.13
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 200m
      memory: 512Mi
  config:
    disable-access-log: 'true'
    keep-alive-requests: '10000'
    upstream-keepalive-connections: '64'
    server-tokens: 'false'
    ssl-ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256'
  extraArgs: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []
  watchNamespace: []

# Config related with default http backend
defaultBackend:
  name: default-http-backend
  replicaCount: 1
  replicas: 1
  imageRegistry: quay.io/opencloudio
  imageDigest: quay.io/opencloudio/default-http-backend@sha256:7cee76c44492269053c38374319e84273fe94dadfcfb97cfddfae9d0b017e786
  image:
    repository: default-http-backend
    tag: 1.5.8
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []

# The init image used to configure some system setting
init:
  imageDigest: quay.io/opencloudio/icp-initcontainer@sha256:87b30476a024b7a3870cd6b68c0f859cd29b908e9c99f07375f3dfb29d00b963
  imageRegistry: quay.io/opencloudio
  image:
    repository: icp-initcontainer
    tag: 1.0.0-build.9
    pullPolicy: IfNotPresent

# The kubectl image used to patch route resource
kubectl:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  imageDigest: quay.io/opencloudio/kubectl@sha256:8f8a010daf257b89fead6bc1bfdb7835ff9054b1cfaaea796304ec8c7e0f5c5d
  imageRegistry: quay.io/opencloudio
  image:
    repository: kubectl
    tag: v1.15.9.5
