# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Whether to enable FIPS
fips_enabled: false

# Config related with ingress nginx controller
ingress:
  name: nginx-ingress-controller
  replicaCount: 1
  hostNetwork: false
  hostPort: false
  httpPort: 80
  httpsPort: 443
  routeHost: cp-proxy.apps.ibm.com
  imageRegistry: quay.io/opencloudio
  image:
    repository: nginx-ingress-controller
    tag: 0.23.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 150Mi
    limits:
      cpu: 200m
      memory: 512Mi
  config:
    disable-access-log: 'true'
    keep-alive-requests: '10000'
    upstream-keepalive-connections: '64'
    server-tokens: 'false'
    ssl-ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256'
  extraArgs: {}
  annotations: {}
  nodeSelector: {}
  tolerations: []

# Config related with default http backend
defaultBackend:
  name: default-http-backend
  replicaCount: 1
  imageRegistry: quay.io/opencloudio
  image:
    repository: default-http-backend
    tag: 1.5.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []

# The init image used to configure some system setting
init:
  imageRegistry: quay.io/opencloudio
  image:
    repository: icp-initcontainer
    tag: 1.0.0-build.2
    pullPolicy: IfNotPresent

# The kubectl image used to patch route resource
kubectl:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  imageRegistry: quay.io/opencloudio
  image:
    repository: kubectl
    tag: v1.15.9
